# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jekyll for Web Designers
email: your-email@domain.com
description: "Companion blog to the lynda.com course, Jekyll for Web Designers. This 
site was designed by James Williamson & Lynda.com to present Jekyll to web designers in a clear, concise way, and
provide a resource and reference for those that are new to Jekyll."
baseurl: "/lynda-jekyll-blog" # the subpath of your site, e.g. /blog
url: "http://jaimemendozadev.github.io/lynda-jekyll-blog" # the base hostname & protocol for your site
github_username:  jaimemendozadev
tagline: "A practice blog and basic guide to Jekyll"

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
theme: minima
gems: [jekyll-paginate]
paginate: 3
paginate_path: '/page:num/'
permalink: :year/:month/:title